version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.1'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: '.'
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --all-groups --frozen'
      - 'bun install'
      - 'bun --cwd=e2e/app neu update'
      - 'lefthook install'
  verify:
    desc: 'Verify workspace'
    cmds:
      - 'lefthook run pre-commit --all-files'
  example-run:
    desc: 'Run example app'
    dir: './example'
    cmds:
      - 'bun x neu run -- {{.CLI_ARGS}}'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
