version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.0'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: '.'
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --all-groups --frozen'
      - 'bun install'
      - 'bun --cwd=e2e/app neu update'
      - 'lefthook install'
  verify:
    desc: 'Verify workspace'
    cmds:
      - 'lefthook run pre-commit --all-files'
  example-run:
    desc: 'Run example app'
    dir: './example'
    cmds:
      - 'bun x neu run -- {{.CLI_ARGS}}'
