"""Host and extension interfaces.

"Host" is alias of Neutralinojs core application.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from .native_api import APIParameters

if TYPE_CHECKING:
    from typing import Any

    from typing_extensions import Self


@dataclass
class Connection:
    """Information for connect to host.

    :ref: https://neutralino.js.org/docs/how-to/extensions-overview#connecting-an-extension-with-neutralinojs
    """

    nlPort: str
    """port of the Neutralinojs server."""
    nlToken: str
    """Access token to use the native API."""
    nlConnectToken: str
    """A token that extension should send during WebSocket connection initialization."""
    nlExtensionId: str
    """Extension identifier."""

    @classmethod
    def from_stdin(cls) -> Self:
        """Create instance from stdin recieved from host."""
        data = json.load(sys.stdin)
        return cls(**data)

    @property
    def url(self) -> str:
        """WebSocket URL of host server."""
        return f"ws://localhost:{self.nlPort}?extensionId={self.nlExtensionId}&connectToken={self.nlConnectToken}"

    @property
    def token(self) -> str:
        """A token to send message from extension to host."""
        return self.nlToken

    def make_message(
        self, method: str, data: APIParameters | Any | None = None
    ) -> Message:
        """Create message instance using connection property."""
        return Message(access_token=self.token, method=method, data=data)


@dataclass
class Message:
    """Format of message sending from extension app to host.

    :ref: https://neutralino.js.org/docs/how-to/extensions-overview#sending-a-message-from-the-extension-to-app
    """

    method: str
    """Native method name. Eg: window.setTitle."""
    access_token: str
    """Access token generated by the Neutralinojs server."""
    data: APIParameters | Any | None = None
    """Parameters for the native method."""
    id: UUID = uuid4()
    """A UUID v4 string."""

    def to_json(self) -> str:
        """Dump as JSON string."""
        msg: dict[str, Any] = {
            "id": str(self.id),
            "method": self.method,
            "accessToken": self.access_token,
        }
        if isinstance(self.data, APIParameters):
            msg["data"] = self.data.asdict()
        elif self.data:
            msg["data"] = self.data
        return json.dumps(msg)
