name: 'Release new version'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.51.2
      - name: Build package
        run: |
          uv build
          ls -l dist
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
  gh-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          bodyFile: '.github/release-body.md'
          draft: false
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          prerelease: false
